### ISSUE TITLE
Request: Rainbow lighting effect

### ISSUE THREAD

**Issue by f0s3** [flozz/rivalcfg#121]
There is an effect is SSE that makes a mouse change it's color from one to another in a cycle. You can pass in any amount of colors and SSE will build a transition between them. It is a very challenging feature to have, but it is (as far as I can see) the only missing lighting feature. Ofc this is a low-priority thing, but rather nice to have. Any thoughts on that?

**Comment by flozz** [comment]
Hello,

Wich mouse are you talking about?

Rivalcfg supports gradients (and it will be improved in v4.0 that will be released in few weeks), but this is only supported for devices that implement it in the hardware.

Some devices like the Rival 310, 600, 700, 710, Sensei 310,... Have an hardware support for this feature so it is (or it will be) supported by rivalcfg.

And some other devices like the Rival 100, 110, 300, 3,... Have no hardware support of color gradient, so it will not be supported by rivalcfg (because it requires to implement a daemon that updates the color, and this is out of the scope of this software for now).

:)

**Comment by flozz** [comment]
I added this question in the FAQ to make this more visible:

https://flozz.github.io/rivalcfg/faq.html#why-rivalcfg-does-not-support-color-gradients-color-shift-rainbow-lighting-effect-on-my-mouse-whereas-the-steelseries-engine-does

Thank you for the issue, it helps improving the doc :)

**Comment by f0s3** [comment]
Sorry for the late reply. I have Rival 100, it's a pity it's not supported, though completely not critical. Thanks for your answer andglad to help you improve the doc :)
