### ISSUE TITLE
Dump current configuration

### ISSUE THREAD

**Issue by gregflynn** [flozz/rivalcfg#16]
Is there a command line flag to dump the current config? I have a rival on my home computer that i configured in windows long ago (this computer runs linux full time now) and i would like to copy that config to my work computer's rival

Is there currently a way to do this or should I dig in and send a PR to add it? Also I guess is it possible to read settings from the mouse with this lib or just write?

Thanks

**Comment by flozz** [comment]
Hello,

Currently I have found no way to read the mouse config and there is no clue that it is possible.

I configured my mouse on a Windows VM the first time, and when I plugged it to a Windows PC with the SteelSeries Engine installed on it, it reseted my config when i tried to modify it... So I think that the SS Engine stores the config on both the mouse end the PC because it cannot read it back.

**Comment by gregflynn** [comment]
Ok, that makes sense, I'm going to take a crack at it when i get some time.  When I give up I will close this issue :)

thanks
