### ISSUE TITLE
Don't assume hardcoded udev rules

### ISSUE THREAD

**Issue by mrjoel** [flozz/rivalcfg#173]
I would like to use a local clone of rivalcfg without doing a system installation of the package. I use an existing system to handle my udev rules files with specific groups. I am not willing to use perm 0666 but use 0660 instead. While this is a more advanced setup, there should not be a technical reason why the udev rules are required to use the specific filename. Please consider having udev rules be a separate configuration step, but during `rivalcfg` execution not assuming or requiring a specific udev config file. It should be sufficient to check presence and permissions for the known set of supported device ids - if they have the needed permissions then make it available for use.

**Comment by flozz** [comment]
Hello,

I do not know of to check permission before trying to open the device and having an error (I do not manipulate directly files in `/dev`, I use a library that abstract the access to HID devices for multiple OS).

If the udev file is not present, Rivalcfg only displays a warning that can be ignored by the end user. This warning and commands to install rules were added because most of the issues reported by users were related to that.

:)
