### ISSUE TITLE
Some little bugs concerning Rival 300 Fade edition

### ISSUE THREAD

**Issue by ghost** [flozz/rivalcfg#29]
I'm on Ubuntu 16.04

1. For some reason I'm unable to add a value for "-b" BTN6_ACTION. Tried with "os" and "default". Nothing changes.
When I click it keeps doing the same value I entered when the mouse settings were changed on Windows 10 with the Steelseries software (a keyboard letter that it was assigned for TeamSpeak mic toggle).

2. Another bug which is more important than the other. Sometimes after resetting Ubuntu, the -s and -S options get resetted and they will jump to a random undesired number I entered before. (for example; 50; 200)

3. The -r and --reset option sometimes work separated and sometimes together. Depends on the timing for entering the commands. Either the wheel will reset, or the logo, or both at the same time.

4. Sometimes you have to enter a command via terminal 2, 3 or up to 4 times to make it work. No idea what causes this.

Is it difficult to write a code that interacts with the mouse and prints the current value for each command? It helps a lot for testing and checking what's going on inside.

Thanks in advance!

**Comment by nicob89** [comment]
I must add, sometimes you have to enter a command via terminal 2, 3 or up to 4 times to make it work. No idea what causes this.

**Comment by flozz** [comment]
Hello,

* `1-2.` I will receive a Rival 300 tomorrow, so I will soon be able to check what is going on with this mouse
* `3-4.` I already saw this problem, sometimes the commands are not sent to the mouse. When I finished fixing the Rival 300 issues (#5, #25, #28 and possibly your `1.`) I will change the way rivalcfg communicate with the mouse. I will use the [hidapi][] lib instead of pyudev+/dev/hidraw* files.

> Is it difficult to write a code that interacts with the mouse and prints the current value for each command?

As far as I know, it is not possible to read values from the mouse so you can just print what values / commands are sent to the mouse.

[hidapi]: https://pypi.python.org/pypi/hidapi/0.7.99.post20

**Comment by nicob89** [comment]
Thanks for the fast response!

**Comment by flozz** [comment]
this should work now. I close the issue
