### ISSUE TITLE
TypeError with -r, -s, and -S options

### ISSUE THREAD

**Issue by defkeh** [flozz/rivalcfg#8]
`TypeError: an integer is required` when running `rivalcfg -r`, `rivalcfg -s`, or  `rivalcfg -S` 

    Traceback (most recent call last):
      File "/usr/bin/rivalcfg", line 9, in <module>
        load_entry_point('rivalcfg==2.4.2', 'console_scripts', 'rivalcfg')()
      File "/usr/lib/python3.5/site-packages/rivalcfg/cli.py", line 176, in main
        mouse.set_default()
      File "/usr/lib/python3.5/site-packages/rivalcfg/rival_mouse.py", line 33, in set_default
        getattr(self, command)(self.profile["commands"][command]["default"])
      File "/usr/lib/python3.5/site-packages/rivalcfg/rival_mouse.py", line 106, in _handler_range
        self._device_write(*merge_bytes(command["command"], command["value_transform"](value)))
      File "/usr/lib/python3.5/site-packages/rivalcfg/rival_mouse.py", line 57, in _device_write
        self._device.write(bytearray(bytes_))
    TypeError: an integer is required

**Comment by flozz** [comment]
I will try to fix that Monday or Tuesday, and I will add some tests to automatically check that everything work on Python 2 and Python 3

**Comment by flozz** [comment]
I am not able to reproduce this bug (I tested with Python 2.7 and Python 3.5 on Ubuntu). 

* Are you able to reproduce with the latest commit from master?
* What is your exact Python version `python --version`?
* What is your Linux distribution?

**Comment by defkeh** [comment]
> Are you able to reproduce with the latest commit from master?

Yes. Updated to `r67.71e0b62` and produces the same message.

> What is your exact Python version `python --version`?

[Python 3.5.2](https://www.archlinux.org/packages/extra/x86_64/python/)

> What is your Linux distribution?

Arch Linux. Output from `uname`: `Linux janus 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux`

**Comment by flozz** [comment]
I will install an Archlinux VM to try to reproduce

**Comment by flozz** [comment]
Hello,

I installed `rivalcfg` using your [AUR package](https://aur.archlinux.org/packages/rivalcfg-git/), I tested in `DEBUG_DRY` mode and it worked fine, but the problem seems to happen when the application tries to write informations to a real device. I will have to wait until tomorrow to test on my own Rival 100.

![capture d ecran de 2016-08-15 20-10-57](https://cloud.githubusercontent.com/assets/971438/17674347/7299aefc-6325-11e6-9a34-8b558adeb4e7.png)

**Comment by defkeh** [comment]
Could it be an issue with pyudev?

**Comment by flozz** [comment]
I tried with the real mouse plugged in, and it worked fine... I cannot figure out what is going wrong... That is a weird issue :( 

![screenshot 2016-08-16 09-08-38](https://cloud.githubusercontent.com/assets/971438/17690869/a66ef004-6391-11e6-84b6-c3c4e0ea690b.png)

> Could it be an issue with pyudev?

It should not, because it is used only to find devices, not to send data to mices.

**Comment by flozz** [comment]
Oh! I think I found the problem... With Python 3, rivalcfg tries to write floating point numbers to the devices (only for Rival and Rival 300). Can you confirm that the last commit fixes the issue?

**Comment by defkeh** [comment]
>  rivalcfg tries to write floating point numbers

I suppose `TypeError: an integer is required` indicates this.

> Can you confirm that the last commit fixes the issue?

`r68.09e6ef8` fixes the issue. Great work! :+1:

**Comment by flozz** [comment]
**rivalcfg 2.4.3** released with this issue fixed :)
